# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '775963a0-17ae-46d1-8e6b-d8814408039e'
  imageRepository: 'demo'
  containerRegistry: 'tdcpoa2020demo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Temperature.Converter.API/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: From Restore to Deploy
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonar'
        organization: 'marcelgol'
        scannerMode: 'MSBuild'
        projectKey: 'marcelgol_tdcpoa2020-demo'
   
    - task: DotNetCoreCLI@2
      displayName: "Dotnet Restore"
      inputs:
        command: 'restore'
        projects: '.'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      displayName: "Dotnet Build"
      inputs:
        command: 'build'
        projects: '.'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: './Temperature.Converter.Tests'

    - task: SonarCloudAnalyze@1

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
        
    - task: DotNetCoreCLI@2
      displayName: "Dotnet Publish"
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: './Temperature.Converter.API'
        arguments: '-o ./Temperature.Converter.API/out'
        zipAfterPublish: false
        modifyOutputPath: false
        
    - task: Docker@2
      displayName: "Docker Build and Push"
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    
    - task: AzureRmWebAppDeployment@4
      displayName: "Deploy to WebApp"      
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Enterprise Subscription(249a316d-fc9d-4e07-bf47-4ab48ab2cb23)'
        appType: 'webAppContainer'
        WebAppName: 'tdcpoa2020-demo-dockerapp'
        DockerNamespace: $(containerRegistry)
        DockerRepository: $(imageRepository)
        DockerImageTag: $(tag)
    
    - task: AzureAppServiceManage@0
      displayName: "Stop WebApp"
      inputs:
        azureSubscription: 'Visual Studio Enterprise Subscription(249a316d-fc9d-4e07-bf47-4ab48ab2cb23)'
        Action: 'Stop Azure App Service'
        WebAppName: 'tdcpoa2020-demo-dockerapp'
    
    - task: AzureAppServiceManage@0
      displayName: "Start WebApp"
      inputs:
        azureSubscription: 'Visual Studio Enterprise Subscription(249a316d-fc9d-4e07-bf47-4ab48ab2cb23)'
        Action: 'Start Azure App Service'
        WebAppName: 'tdcpoa2020-demo-dockerapp'
